# Generated by Django 4.2.5 on 2023-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wyporzyczalnia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='comments',
            field=models.ManyToManyField(to='Wyporzyczalnia_app.comments'),
        ),
    ]
