# Generated by Django 4.2.5 on 2023-09-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wyporzyczalnia_app', '0002_machinery_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='rental',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wyporzyczalnia_app.rental'),
        ),
    ]
