# Generated by Django 4.2.5 on 2023-09-21 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wyporzyczalnia_app', '0004_ratings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Ocena musi być większa lub równa 1.'), django.core.validators.MaxValueValidator(5, 'Ocena musi być mniejsza lub równa 5.')]),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
